name: Deploy Documentation

on:
  push:
    branches:
      - main  # Déploiement automatique après un push sur main

permissions:
  contents: write  # ✅ Ajoute cette ligne pour donner les droits d'écriture

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Documentation
        run: npm run docs

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs